config/routes.rb
ProtoSynth::Application.routes.draw do

  
  root :to => 'login#login'

  get "project_links/new"
  match '/submissions',   to: 'project_links#submissions',       via: 'get'
  match '/login',               to: 'login#login',            via: 'get'
  match '/login_check',         to: 'login#login_check',    via: 'post'
  match '/logout',              to: 'login#logout',          via: 'get'

  match '/new',         to: 'login#new',         via: 'get'
  match '/create',      to: 'login#create',      via: 'post'

  match '/home',             to: 'first_pages#home',            via: 'get'
  get "first_pages/help"
  
  match '/recommended_links',   to:'first_pages#recommended_links',   via: 'get'
  match '/glove_mouse',   to:'first_pages#glove_mouse',   via: 'get'
  match '/android_bot',   to:'first_pages#android_bot',   via: 'get'
  match '/speakers',   to:'first_pages#speakers',   via: 'get'
  match '/about',   to:'first_pages#about',   via: 'get'
  match '/projects',   to:'first_pages#projects',   via: 'get'

  resources :users
  resources :videos, only: [:index, :new, :create]

end

app/models/projects.rb
class Projects < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #needed to exist for login to render correctly
  #attr_accessor :username, :first_name, :last_name, :password, :password_confirmation, :walldate
  has_secure_password
  attr_accessible :username, :first_name, :last_name, :password, :password_confirmation
  has_many :posts
  has_many :friendships
  has_many :pending_friendships
  
   #validates :username, uniqueness: {message: "already taken!"}, presence: true, format: {with: /\A[a-zA-Z0-9]+\Z/, message: "must be alphanumeric and no spaces!"}
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :password, confirmation: true
  # #validates :walldate, presence: true
end

app/models/video.rb
class Video < ActiveRecord::Base

	attr_accessible :link

	YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([\A#\&\?]*).*/i

	validates :link, presence: true, format: YT_LINK_FORMAT

	before_create -> do	
		uid = link.match(YT_LINK_FORMAT)
		self.uid = uid[2] if uid && uid[2]

		if self.uid.to_s.length != 11
			self.errors.add(:link, 'is invalid.')
			false
		elsif Video.where(uid: self.uid).any?
			self.errors.add(:link, 'is not unique.')
			false
		else
			get_additional_info
		end
	end

	private

	def get_additional_info
		begin
			client = YouTubeIt::OAuth2Client.new(dev_key: '') # fill in dev key here
			video = client.video_by(uid)
			self.title = video.title
			self.duration = parse_duration(video.duration)
			self.author = video.author.name
			self.likes = viedo.rating.likes
			self.dislikes = video.rating.dislikes
		rescue
			self.title = '' ; self.duration = '00:00:00' ; self.author = '' ; self.likes = ''
		end
	end

	def parse_duration(d)
		hr = (d / 3600).floor
		min = ((d-(hr * 3600)) / 60).floor
		sec = (d - (hr * 3600) - (min * 60)).floor

		hr = '0' + hr.to_s if hr.to_i < 10
		min = '0' + min.to_s if min.to_i < 10
		sec = '0' + sec.to_s if sec.to_i < 10

		hr.to_s + ':' + min.to_s + ':' + sec.to_s
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  

end

app/controllers/first_pages_controller.rb
class FirstPagesController < ApplicationController
  def home
  end

  def help
  end

  def glove_mouse
  end

  def recommended_links
    
  end
  def android_bot
  end
  def speakers
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
 #before_filter :redirect_if_not_logged_in, only: [:friends, :preferences, :update, :clear_wall]

  def login
    if session.has_key?(:login_id) # If logged in already
      @current_user = User.find(session[:login_id]) # Set current user for header
    end
  end

  def login_check #Check if supplied data (from params) is actually a username/password combo
    @potential_users = User.find(:all, :conditions => {:username => params[:login][:username]})
    if @potential_users.length != 1 # No user found
      flash[:notice] = "Username not found!"
      redirect_to login_path
    elsif @potential_users[0].authenticate(params[:login][:password]) # Only one user found and it was the right password
      session[:login_id] = @potential_users[0].id
      @current_user = @potential_users[0]
      redirect_to home_path
      flash[:notice] = "dub tee brah"
    else # Password was wrong
      flash[:notice] = "wrong password"
      redirect_to login_path
    end
  end

  def logout
    session[:login_id] = nil # Clear session variable to logout
    redirect_to login_path
  end

  def new # Page with form to create a new user
    @user=User.new
    if session.has_key?(:login_id) # If logged in already
      @current_user = User.find(session[:login_id]) # Set current user for header
    end
  end
  def create # Creates a new user, no view associated with it
      @user = User.new(user_params) # Create new user
      if @user.save
        @current_user = @user
        session[:login_id] = @current_user.id
        redirect_to home_path # Redirect to Newsfeed
      else # An error was found
        flash[:error]="errors in this bitch"
        logger.info "errors in Create"
        #flash[:error] = @new_user.errors.full_messages()[0] # Display error to user
        redirect_to new_path # Redirect to make new account
      end
  end
  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :password, :password_confirmation)
  end
  
end

app/controllers/project_links_controller.rb
class ProjectLinksController < ApplicationController
 	def submissions
  		ordering = params[:order] || 'hot'
  		order  = case ordering
              	  when 'hot' then 'points DESC'
              	  when 'new' then 'created_at DESC'
                end
  		# @link_pages, @links = Projects.paginate :page=>params[:page], :order=> order, :per_page => 20
  		@header_text = case ordering
			  when 'hot' then 'Top rated submissions'
			  when 'new' then 'Latest submissions'
      end
  end

	def modify_points
		@link = Link.find(params[:id])
		@link.update_attribute :points, @link.points + params[:by].to_i if params[:by] =~ /[+|-]?1/
		render_text @link.points
  end
	def new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end
	def create
		@user = User.new(user_params) # Create new user
		if @user.save
			#@current_user = @user
			#session[:login_id] = @current_user.id
			redirect_to home_path # Redirect to Newsfeed
		else # An error was found
			flash[:error]="errors in this page"
			logger.info "errors in Create"
			#flash[:error] = @new_user.errors.full_messages()[0] # Display error to user
			redirect_to new_path # Redirect to make new account
		end
	end
	def user_params
    	params.require(:user).permit(:username, :first_name, :last_name, :password, :password_confirmation)
  	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  

  def new
    @video = Video.new
  end


  def create
    @video = Video.new(video_params)
    if @video.save
        flash[:success] = 'Video Added!'
        redirect_to root_url
    else
      flash[:error]="errors in video page"
      logger.info "erros in video page"
      redirect_to home_path
    end
  end

  def video_params
    params.require(:video).permit(:link)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_pages_helper.rb
module FirstPagesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/project_links_helper.rb
module ProjectLinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/first_pages/about.html.haml
=provide(:title, 'About')

=render 'layouts/project_side_links'
%div.container
	%center
		%h3 About
	

app/views/first_pages/android_bot.html.haml
=provide(:title, 'Andriod Controlled Robot')


=render 'layouts/project_side_links'
%div.container
	%center
		%h3 Android Controlled Robot
		/@video_id = Zy_EhCOInMc 
		%br
		%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/F9Fqfbpoy68", :title => "YouTube video player", :width => "640"}
		/ iframe width="560" height="315" src="//www.youtube.com/embed/Zy_EhCOInMc" frameborder="0" allowfullscreen
		/#{@video_id}

app/views/first_pages/glove_mouse.html.haml
=provide(:title, 'Glove Mouse')

=render 'layouts/project_side_links'
%div.container
	%center
		%h3 Glove Mouse
		/@video_id = Zy_EhCOInMc 
		%br
		%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/Zy_EhCOInMc", :title => "YouTube video player", :width => "640"}
		/ iframe width="560" height="315" src="//www.youtube.com/embed/Zy_EhCOInMc" frameborder="0" allowfullscreen
		/#{@video_id}

app/views/first_pages/help.html.erb
<h1>FirstPages#help</h1>
<p>Find me in app/views/first_pages/help.html.erb</p>

app/views/first_pages/home.html.haml
=provide(:title, 'Login')

%br
%center
  %h1 ProtoSynthesis
  /@video_id = Zy_EhCOInMc 
  %br
  %iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/Zy_EhCOInMc", :title => "YouTube video player", :width => "640"}
  / iframe width="560" height="315" src="//www.youtube.com/embed/Zy_EhCOInMc" frameborder="0" allowfullscreen
  /#{@video_id}

app/views/first_pages/projects.html.haml
=provide(:title, 'Projects')

=render 'layouts/project_side_links'
%div.container
	%center
		%h3 Projects
				
		

app/views/first_pages/recommended_links.html.haml
=provide(:title, 'Recommended Links')

%br
%br
%center
	%h3 Recommended links
  
	/ %br
	/ %section
	/ %br
	/ %h5 Recommended Articles
	/ %div
	%ul
		%br
		%li= link_to "Why FPGA's will take over ASIC's", "http://www.embeddedrelated.com/showarticle/195.php"
		%li= link_to "Reddit ECE", "http://www.reddit.com/r/ece"
		%li= link_to "Jeremy Blum beginner Arduino Tutorials", "http://www.jeremyblum.com/category/arduino-tutorials/"
		%li= link_to "Hackaday (Maker Projects)", "http://hackaday.com/"
		%li= link_to "EEVblog (product breakdowns)", "http://www.eevblog.com/"
		%li= link_to 'Sparkfun (project parts\ideas)', "https://www.sparkfun.com/"
		%br
		%h4 Nintendo 64 Breakdown
		%br
		%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/ScicrgZwvg4", :title => "YouTube video player", :width => "640"}

app/views/first_pages/speakers.html.haml
=provide(:title, 'Coke Can Speaker')


=render 'layouts/project_side_links'
%div.container
	%center
		%h3 Coke Can Speaker
		/@video_id = Zy_EhCOInMc 
		%br
		%iframe{:allowscriptaccess => "always", :allowFullScreen => "true", :frameborder => "0", :height => "430", :src => "http://www.youtube.com/embed/mfL_ZQ3mFj0", :title => "YouTube video player", :width => "640"}
		/ iframe width="560" height="315" src="//www.youtube.com/embed/Zy_EhCOInMc" frameborder="0" allowfullscreen
		/#{@video_id}

app/views/layouts/_header.html.haml
%header{:class => "navbar navbar-fixed-top navbar-inverse"}
  %div{:class => "navbar-inner"}
    %div{:class => "container"}

app/views/layouts/_project_side_links.html.haml
%br
%br
	%div
		%div.carousel.sidebar.slider.mini.navbar-inverse.fluid.facebook
			%ul.nav-stacked.navbar-inner.sidebar.carousel.sidebar.slider.mini.navbar-inverse.fluid.facebook#left_links
				%h4= link_to 'Kinect Glove Mouse', glove_mouse_path
				%h4= link_to 'Recommended Links', recommended_links_path
				%h4= link_to 'Android Controlled Robot', android_bot_path
				%h4= link_to 'Coke Can Speaker', speakers_path

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title= yield(:title)
		= stylesheet_link_tag :application, :media => "all"
		= javascript_include_tag :application
		= csrf_meta_tags

		%body
			%header.navbar.navbar-fixed-top.navbar-invers
				%div.navbar-inner
					%div.container
						%center
							%br
							%h1 ProtoSynthesis
							%nav
								%ul.nav.pull-left
									%li= link_to 'Home', home_path
									%li= link_to 'About', about_path
									%li= link_to 'Projects', projects_path
									%li= link_to 'Recommended Links', recommended_links_path
									%li= link_to 'Upload', new_video_path, class: 'btn btn-primary btn-lg'
								%ul.nav.pull-right
									-if session[:login_id].present? 
										%li= link_to 'Log Out', logout_path
									-else
										%li= link_to 'Log In', login_path
			%br						
			%div{:id => "content"}
			= yield

app/views/login/login.html.haml
=provide(:title, 'Login')

%br
%br
%br
%center
  %h1 ProtoSynthesis Login Page
  %br
  =form_tag login_check_path do
    //= render 'shared/error_messages'
    //%p id="notice"
    = flash[:notice]
    = label :login, :username, 'Username'
    = text_field :login, :username

    = label :login, :password, 'Password'
    = password_field :login, :password
    %br
    = submit_tag 'Login', :class => "btn btn-info"


  %h4= link_to 'Make new account', new_path

app/views/login/new.html.haml
=provide(:title, 'Create New Account')

%br
%br
%br
%center
    %h1 Create New Account Page
    %br
    = form_for(@user, :url => {:action =>"create"}) do |f|
        //= render 'shared/error_messages'
        = f.label :username, 'Username'
        = f.text_field :username
        %br
        = f.label :first_name, 'First name'
        = f.text_field :first_name
        %br
        = f.label :last_name, 'Last name'
        = f.text_field :last_name
        %br
        = f.label :password, 'Password'
        = f.password_field :password
        %br
        = f.label :password_confirmation, 'Confirm password'
        = f.password_field :password_confirmation
        %br
        //= label  :interests, 'Interests'
        //= text_field  :interests
        //%br
        //= label  :quotes, 'Quotes'
        //= text_field  :quotes
        //%br
        = f.submit 'Create Account', :class => "btn btn-info"

app/views/project_links/new.html.haml
%h1 ProjectLinks#new
%p Find me in app/views/project_links/new.html.haml

app/views/project_links/submissions.html.haml
=provide(:title, 'Submissions')

= javascript_include_tag :defaults
%br
%center
	%h1 =@header_text
	=link_to "Hot", {:action=> 'submissions', :order =>'hot'} 
	=link_to "New", {:action=> 'submissions', :order =>'new'} 
	=link_to 'Add new link', :action => 'new'

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml

app/views/videos/new.html.haml
=provide(:title, 'New Video')

=render 'layouts/project_side_links'
%div.container
	%center
		%h3 New Video

		= form_for @video do |f|
			/ =render 'shared/errors', object: @video
			%div{:class => "form-group"}
				= f.label :link
				= f.text_field :link, class: 'form-control', required: true
				/%span{class => "help-block"} 
				/	A link to the vid on youtube
			= f.submit class: 'btn btn-default'

app/views/videos/newVid.html.haml
=provide(:title, 'New Video')

=render 'layouts/project_side_links'
%div.container
	%center
		%h3 New Video
	